version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 13f881b33ee725128dad03f66276972cf5ac00d321f90237e3f0eaf71fe5925a

    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Set up Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Run tests
          command: |
              ./cc-test-reporter before-build
              yarn test --coverage
              ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
